import fs from 'node:fs';
import path from 'node:path';

// All routes that must exist in the static export.
// Redirect stubs (generated by scripts/generate-redirects.mjs) keep the
// old root-to-guide URLs working with a meta-refresh.
const baselineRoutes = [
  '/', '/docs/', '/install/', '/getting-started/', '/interfaces-and-data/', '/updating/', '/faq/',
  '/themes/',
  '/library/', '/importing/', '/organizing/', '/queue-tags-notifications/',
  '/metadata-and-media/', '/emulators-and-launching/', '/big-box-and-handhelds/',
  '/handheld-performance/', '/sessions-saves-and-backups/', '/troubleshooting/',
  '/retroachievements/', '/plugins/', '/discovery/', '/storefront-manager/',
  '/media-providers/', '/search-syntax/',
  '/integrations/import-sources/', '/integrations/accounts-and-media/', '/integrations/local-services/', '/integrations/webhooks/',
  '/guides/library/', '/guides/library/importing/', '/guides/library/export/', '/guides/library/navigation/', '/guides/library/organizing/', '/guides/library/queue-tags-notifications/', '/guides/library/setup-center/', '/guides/library/insights/', '/guides/metadata-and-media/', '/guides/emulators-and-launching/', '/guides/big-box-and-handhelds/', '/guides/big-box-and-handhelds/performance/', '/guides/sessions-saves-and-backups/', '/guides/sessions-saves-and-backups/saves/', '/guides/sessions-saves-and-backups/library-backups/', '/guides/sessions-saves-and-backups/statistics-sync/', '/guides/sessions-saves-and-backups/activity-center/', '/guides/sessions-saves-and-backups/library-sync/', '/guides/troubleshooting/', '/guides/troubleshooting/startup-and-browser/', '/guides/troubleshooting/imports/', '/guides/troubleshooting/metadata-and-media/', '/guides/troubleshooting/launching/', '/guides/troubleshooting/state-recovery/', '/guides/troubleshooting/backups-and-restores/', '/guides/troubleshooting/integration-credentials/', '/guides/troubleshooting/plugins/', '/guides/troubleshooting/diagnostic-logs/', '/guides/retroachievements/', '/guides/plugins/', '/guides/plugins/creating-a-plugin/', '/guides/discovery/', '/guides/storefront-manager/', '/guides/media-providers/', '/guides/integrations/faugus/', '/guides/themes/custom-themes/', '/guides/wine-and-proton/', '/reference/search-syntax/', '/reference/save-archives/', '/reference/library-backups/', '/reference/background-jobs/', '/reference/api/overview/', '/reference/api/library-and-settings/', '/reference/api/automation/', '/reference/api/content-and-imports/', '/reference/api/saves-and-operations/', '/reference/api/local-admin/', '/reference/api/screenscraper-and-export/', '/reference/plugins/overview/', '/reference/plugins/manifest/', '/reference/plugins/hooks/', '/reference/plugins/process-and-errors/', '/reference/plugins/catalog/',
  '/reference/configuration/', '/reference/cli/', '/reference/command-tokens/', '/reference/data-and-recovery/', '/reference/how-it-works/', '/reference/api/', '/reference/plugins/', '/reference/parity/', '/reference/shortcuts/', '/reference/hardware-matrix/', '/reference/architecture/',
  '/steam-deck/', '/localization/', '/changelog/', '/roadmap/',
  '/downloads/', '/compare/', '/showcase/', '/enterprise/',
  '/project/contributing/', '/project/design-system/', '/project/releasing/', '/policies/security/', '/policies/privacy/', '/policies/legal-and-trademarks/', '/policies/dmca/', '/reference/architecture/frontend-modules/',
  '/search/'
];

// Keep the gate aligned with authored content as the docs grow. The baseline
// above covers the public landing pages and legacy redirect stubs; this walk
// adds every real Markdown page automatically, including new nested guides.
const authoredRoutes = new Set();
const docsRoot = path.join(process.cwd(), 'content', 'docs');

function collectAuthoredRoutes(dir, prefix = '') {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      collectAuthoredRoutes(fullPath, `${prefix}${entry.name}/`);
      continue;
    }
    if (!entry.name.endsWith('.md') && !entry.name.endsWith('.mdx')) continue;
    if (entry.name === '404.md' || entry.name === '404.mdx') continue;
    const base = entry.name.replace(/\.mdx?$/, '');
    const slug = base === 'index' ? prefix.slice(0, -1) : `${prefix}${base}`;
    authoredRoutes.add(slug ? `/${slug}/` : '/docs/');
  }
}

collectAuthoredRoutes(docsRoot);

export const requiredRoutes = [...new Set([...baselineRoutes, ...authoredRoutes])];
